#!/bin/sh

make rust_test RUSTFLAGS="-g"
exec gdb -tui \
	-ex 'la sp' \
	-ex 'b rust_test::main' \
	-ex r \
	-ex 'tb __rust_dealloc' \
	-ex ni \
	-ex ni \
	-ex ni \
	-ex 'set $adr = $rax' \
	-ex n \
	-ex n \
	-ex ni \
	-ex ni \
	-ex ni \
	-ex ni \
	-ex ni \
	-ex ni \
	-ex ni \
	-ex ni \
	-ex ni \
	-ex ni \
	-ex ni \
	-ex ni \
	-ex ni \
	-ex 'set $rsp = $rsp - 8' \
	-ex 'set *($rsp as *mut usize) = $rip' \
	-ex 'disp/x $adr' \
	-ex 'disp/x $rdi' \
	-ex 'j *0x5555555578c0' \
	rust_test
